apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: cr.yandex/crpmiu1h5mdish4lqlu2/api:0.0.1
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI 
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: uri


---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30002


