apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: <NONGO_USERNAME>
  password: <MONGO_PASSWORD>
  uri: <MONGO_URI> # https://www.mongodb.com/docs/manual/reference/connection-string/ 


---

apiVersion: v1
kind: Secret
metadata: 
  name: redis-secret
type: Opaque
data:
  redis-password: <REDIS_PASSWORD>


---

apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
type: Opaque
data:
  username: <KAFKA_USERNAME>
  password: <KAFKA_PASSWORD>

