apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-proxy-deployment
  labels:
    app: message-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-proxy
  template:
    metadata:
      labels:
        app: message-proxy
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "message-proxy"
        dapr.io/app-port: "3000"
    spec:
      containers:
        - name: message-proxy
          image: ghcr.io/a-la-fois/message-proxy:0.0.34
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: prod-secrets
                  key: kafka_username
            - name: KAFKA_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: prod-secrets
                  key: kafka_password
            - name: KAFKA_CHANGES_TOPIC 
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: kafka-changes-topic
            - name: KAFKA_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: kafka-hosts 
            - name: KAFKA_CA_PATH
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: yc-ca-path
            - name: KAFKA_SASL_MECHANISM 
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: kafka-sasl-mechanism
            - name: DAPR_SIDECAR_HOST
              value: "localhost"

          volumeMounts:
            - name: yc-cert
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: yc-cert
          configMap:
            name: config
            items:
              - key: 'YandexCA.crt'
                path: 'YandexCA.crt'


---

apiVersion: v1
kind: Service
metadata:
  name: message-proxy-service
spec:
  selector:
    app: message-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: message-proxy-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - ws.alafois.dev
      secretName: tls-secret
  rules:
    - host: ws.alafois.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: message-proxy-service
              port:
                number: 80
