apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tls-secret-store
spec:
  provider:
    yandexcertificatemanager:
      auth:
        authorizedKeySecretRef:
          name: yc-auth
          key: authorized-key

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tls
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tls-secret-store
    kind: SecretStore
  target:
    name: tls-secret
    template:
      type: kubernetes.io/tls
  data:
  - secretKey: tls.crt
    remoteRef:
      key: fpq68l5u9hq32sjl5g4g
      property: chain
  - secretKey: tls.key
    remoteRef:
      key: fpq68l5u9hq32sjl5g4g
      property: privateKey
